### ISSUE TITLE
error to Execultar gulp command

### ISSUE THREAD

**Issue by gerardo-junior** [devmark/laravel-angular-cms#12]
Error: watch ENOSPC

at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at Gaze._watchDir (/home/gerardo/projetos/laravel-angular-cms/backend/node_modules/gaze/lib/gaze.js:289:30)
    at /home/gerardo/projetos/laravel-angular-cms/backend/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/home/gerardo/projetos/laravel-angular-cms/backend/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/home/gerardo/projetos/laravel-angular-cms/backend/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/home/gerardo/projetos/laravel-angular-cms/backend/node_modules/gaze/lib/gaze.js:354:10)
    at Gaze.add (/home/gerardo/projetos/laravel-angular-cms/backend/node_modules/gaze/lib/gaze.js:177:8)
    at new Gaze (/home/gerardo/projetos/laravel-angular-cms/backend/node_modules/gaze/lib/gaze.js:74:10)

**Comment by whcmark** [comment]
Hello, what npm version you are using?

**Comment by gerardo-junior** [comment]
npm@3.3.5 ,
I am developing a similar project with this , and practically , his is the one who found, you know each other?

**Comment by whcmark** [comment]
Will test npm 3 version soon. please use npm 2 at the moment

This project own myself. i don't know others. If you would like to develop together . contact me.

**Comment by gerardo-junior** [comment]
yes , I want to work on this project , I hope can make this project grow

My idea is to create a front end page for demo

and sorry for any errors do not speak English errors are graces of the translator google
